name: assignment-test

on:
  push:
    branches:
      - '*'   # runs on any branch
    tags-ignore:
      - '*'

jobs:
  full-test:
    # Container preconfigured with the AESD autotest environment
    container: cuaesd/aesd-autotest:24-assignment7-buildroot
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run AESD autotest
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          ./clean.sh
          ./build.sh
          ./assignment-autotest/test/assignment8-buildroot/runqemu.sh

      - name: Cleanup SSH keys
        if: always()
        run: ssh-add -D

